import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import LeaguePage from './components/LeaguePage';
import LeagueDetail from './components/LeagueDetail';
import SeasonPage from './components/SeasonPage';
import PlayerSearchSeason from './components/PlayerSearchSeason';
import HeadToHeadWrapper from './components/HeadToHeadWrapper';
import TournamentSearchSeason from './components/TournamentSearchSeason';
import { do_elo, do_glicko2, finish_h2h } from './helpers';
import HeadToHeadChart from './components/HeadToHeadChart';

const App = () => {
  let h2h = {
    Sola: {
      id: 1,
      Syrup: { wins: 0, losses: 0 },
      Jakal: { wins: 0, losses: 0 },
      WebbJP: { wins: 0, losses: 0 },
      Pharaoh: { wins: 0, losses: 0 },
      Leon: { wins: 0, losses: 0 },
      Rivers: { wins: 0, losses: 0 },
      AppleReviewer: { wins: 0, losses: 0 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 0, losses: 0 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 2, losses: 2 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 1, losses: 1 },
      Delta: { wins: 0, losses: 0 },
      Phantum: { wins: 0, losses: 0 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 0, losses: 0 },
      Gonz: { wins: 0, losses: 0 },
      GregHouse: { wins: 0, losses: 0 },
      Yeast: { wins: 0, losses: 0 },
      Tay: { wins: 0, losses: 0 },
      Petayaa: { wins: 0, losses: 0 },
      Haze: { wins: 0, losses: 0 },
    },
    Syrup: {
      id: 2,
      Jakal: { wins: 2, losses: 0 },
      WebbJP: { wins: 1, losses: 0 },
      Pharaoh: { wins: 4, losses: 0 },
      Leon: { wins: 1, losses: 0 },
      Rivers: { wins: 0, losses: 0 },
      AppleReviewer: { wins: 1, losses: 1 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 5, losses: 0 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 2, losses: 1 },
      Delta: { wins: 1, losses: 0 },
      Phantum: { wins: 2, losses: 0 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 1, losses: 0 },
      Gonz: { wins: 0, losses: 0 },
      GregHouse: { wins: 1, losses: 0 },
      Yeast: { wins: 1, losses: 0 },
      Tay: { wins: 0, losses: 0 },
      Petayaa: { wins: 0, losses: 0 },
      Haze: { wins: 1, losses: 0 },
    },
    Jakal: {
      id: 3,
      WebbJP: { wins: 4, losses: 2 },
      Pharaoh: { wins: 0, losses: 0 },
      Leon: { wins: 1, losses: 3 },
      Rivers: { wins: 2, losses: 0 },
      AppleReviewer: { wins: 1, losses: 0 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 0, losses: 0 },
      Justin: { wins: 1, losses: 0 },
      BeatyBean: { wins: 2, losses: 0 },
      Seel: { wins: 1, losses: 0 },
      Smashbros: { wins: 1, losses: 0 },
      Delta: { wins: 2, losses: 0 },
      Phantum: { wins: 0, losses: 0 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 0, losses: 0 },
      Gonz: { wins: 2, losses: 0 },
      GregHouse: { wins: 0, losses: 0 },
      Yeast: { wins: 1, losses: 0 },
      Tay: { wins: 0, losses: 0 },
      Petayaa: { wins: 0, losses: 0 },
      Haze: { wins: 0, losses: 0 },
    },
    WebbJP: {
      id: 4,
      Pharaoh: { wins: 2, losses: 0 },
      Leon: { wins: 0, losses: 0 },
      Rivers: { wins: 1, losses: 0 },
      AppleReviewer: { wins: 0, losses: 0 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 3, losses: 0 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 1, losses: 1 },
      Smashbros: { wins: 0, losses: 0 },
      Delta: { wins: 0, losses: 0 },
      Phantum: { wins: 1, losses: 0 },
      Ram: { wins: 1, losses: 0 },
      Synnister: { wins: 1, losses: 0 },
      Mateo: { wins: 0, losses: 0 },
      Gonz: { wins: 0, losses: 0 },
      GregHouse: { wins: 0, losses: 0 },
      Yeast: { wins: 0, losses: 0 },
      Tay: { wins: 0, losses: 0 },
      Petayaa: { wins: 0, losses: 0 },
      Haze: { wins: 1, losses: 0 },
    },
    Pharaoh: {
      id: 5,
      Leon: { wins: 0, losses: 2 },
      Rivers: { wins: 0, losses: 2 },
      AppleReviewer: { wins: 1, losses: 0 },
      Steffen: { wins: 1, losses: 1 },
      Marvale: { wins: 2, losses: 1 },
      Justin: { wins: 1, losses: 0 },
      BeatyBean: { wins: 0, losses: 1 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 1, losses: 0 },
      Delta: { wins: 0, losses: 3 },
      Phantum: { wins: 4, losses: 1 },
      Ram: { wins: 0, losses: 1 },
      Synnister: { wins: 3, losses: 0 },
      Mateo: { wins: 0, losses: 1 },
      Gonz: { wins: 1, losses: 0 },
      GregHouse: { wins: 1, losses: 0 },
      Yeast: { wins: 0, losses: 0 },
      Tay: { wins: 0, losses: 0 },
      Petayaa: { wins: 2, losses: 0 },
      Haze: { wins: 0, losses: 0 },
    },
    Leon: {
      id: 6,
      Rivers: { wins: 0, losses: 0 },
      AppleReviewer: { wins: 0, losses: 0 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 2, losses: 0 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 0, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 2, losses: 0 },
      Delta: { wins: 2, losses: 0 },
      Phantum: { wins: 3, losses: 1 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 1 },
      Mateo: { wins: 1, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 2, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Rivers: {
      id: 7,
      AppleReviewer: { wins: 0, losses: 0 },
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 1, losses: 0 },
      Justin: { wins: 1, losses: 0 },
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 0, losses: 0 },
      Delta: { wins: 0, losses: 0 },
      Phantum: { wins: 0, losses: 0 },
      Ram: { wins: 1, losses: 0 },
      Synnister: { wins: 1, losses: 0 },
      Mateo: { wins: 0, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 0},
      Haze: { wins: 1, losses: 0},
    },
    AppleReviewer: {
      id: 8,
      Steffen: { wins: 0, losses: 0 },
      Marvale: { wins: 2, losses: 1 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 0, losses: 0 },
      Delta: { wins: 1, losses: 0 },
      Phantum: { wins: 1, losses: 0 },
      Ram: { wins: 1, losses: 0 },
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 0, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 1, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Steffen: {
      id: 9,
      Marvale: { wins: 0, losses: 1 },
      Justin: { wins: 0, losses: 0 },
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 1, losses: 0 },
      Delta: { wins: 0, losses: 0 },
      Phantum: { wins: 0, losses: 0 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 0, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Marvale: {
      id: 10,
      Justin: { wins: 1, losses: 0 },
      BeatyBean: { wins: 4, losses: 0 },
      Seel: { wins: 1, losses: 0 },
      Smashbros: { wins: 1, losses: 0 },
      Delta: { wins: 7, losses: 0 },
      Phantum: { wins: 4, losses: 1 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 4, losses: 2 },
      Mateo: { wins: 5, losses: 0},
      Gonz: { wins: 1, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 3, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 1},
      Haze: { wins: 1, losses: 2},
    },
    Justin: {
      id: 11,
      BeatyBean: { wins: 1, losses: 0 },
      Seel: { wins: 0, losses: 0 },
      Smashbros: { wins: 1, losses: 3 },
      Delta: { wins: 2, losses: 1 },
      Phantum: { wins: 1, losses: 2 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 0, losses: 1 },
      Mateo: { wins: 1, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 1, losses: 0},
      Yeast: { wins: 1, losses: 1},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    BeatyBean: {
      id: 12,
      Seel: { wins: 2, losses: 2 },
      Smashbros: { wins: 4, losses: 3 },
      Delta: { wins: 1, losses: 1 },
      Phantum: { wins: 1, losses: 3 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 1, losses: 2 },
      Mateo: { wins: 1, losses: 1},
      Gonz: { wins: 1, losses: 1},
      GregHouse: { wins: 1, losses: 1},
      Yeast: { wins: 2, losses: 3},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 0},
      Haze: { wins: 2, losses: 0},
    },
    Seel: {
      id: 12,
      Smashbros: { wins: 0, losses: 1 },
      Delta: { wins: 1, losses: 0 },
      Phantum: { wins: 1, losses: 1 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 1, losses: 0 },
      Mateo: { wins: 1, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 1, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 2},
      Haze: { wins: 0, losses: 0},
    },
    Smashbros: {
      id: 12,
      Delta: { wins: 0, losses: 1 },
      Phantum: { wins: 1, losses: 4 },
      Ram: { wins: 1, losses: 1 },
      Synnister: { wins: 0, losses: 1 },
      Mateo: { wins: 2, losses: 0},
      Gonz: { wins: 1, losses: 2},
      GregHouse: { wins: 0, losses: 2},
      Yeast: { wins: 1, losses: 2},
      Tay: { wins: 0, losses: 1},
      Petayaa: { wins: 0, losses: 3},
      Haze: { wins: 0, losses: 4},
    },
    Delta: {
      id: 13,
      Phantum: { wins: 2, losses: 0 },
      Ram: { wins: 0, losses: 0 },
      Synnister: { wins: 3, losses: 1 },
      Mateo: { wins: 2, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 1, losses: 1},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Phantum: {
      id: 14,
      Ram: { wins: 1, losses: 0 },
      Synnister: { wins: 2, losses: 0 },
      Mateo: { wins: 3, losses: 0},
      Gonz: { wins: 1, losses: 1},
      GregHouse: { wins: 1, losses: 1},
      Yeast: { wins: 1, losses: 1},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 1},
      Haze: { wins: 0, losses: 0},
    },
    Ram: {
      id: 15,
      Synnister: { wins: 0, losses: 0 },
      Mateo: { wins: 1, losses: 0},
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 1, losses: 1},
    },
    Synnister: {
      id: 16,
      Mateo: { wins: 0, losses: 1},
      Gonz: { wins: 0, losses: 2},
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 1, losses: 1},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 1},
      Haze: { wins: 0, losses: 0},
    },
    Mateo: {
      id: 17,
      Gonz: { wins: 0, losses: 0},
      GregHouse: { wins: 1, losses: 0},
      Yeast: { wins: 2, losses: 1},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 1, losses: 0},
      Haze: { wins: 1, losses: 0},
    },
    Gonz: {
      id: 18,
      GregHouse: { wins: 0, losses: 0},
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 1},
      Haze: { wins: 0, losses: 0},
    },
    GregHouse: {
      id: 19,
      Yeast: { wins: 0, losses: 0},
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Yeast: {
      id: 20,
      Tay: { wins: 0, losses: 0},
      Petayaa: { wins: 0, losses: 2},
      Haze: { wins: 0, losses: 1},
    },
    Tay: {
      id: 21,
      Petayaa: { wins: 0, losses: 0},
      Haze: { wins: 0, losses: 0},
    },
    Petayaa: {
      id: 22,
      Haze: { wins: 0, losses: 0},
    },
    Haze: {
      id: 23
    }
  }
  h2h = do_elo(h2h)
  h2h = do_glicko2(h2h)
  h2h = finish_h2h(h2h)
  return (
    // <Router>
    //   <Routes>
    //     <Route path="/regions" element={<LeaguePage />} />
    //     <Route path="/regions/:regionId" element={<LeagueDetail />} />
    //     <Route path="/regions/:regionId/seasons/:seasonName" element={<SeasonPage />} />
    //     <Route path="/regions/:regionId/seasons/:seasonName/players" element={<PlayerSearchSeason/>} />
    //     <Route path="/regions/:regionId/seasons/:seasonName/tournaments" element={<TournamentSearchSeason/>} />
    //     <Route path="/regions/:regionId/seasons/:seasonName/h2h-chart" element={<HeadToHeadWrapper/>} />
    //   </Routes>
    // </Router>
    <HeadToHeadChart data={h2h} />
  );
};

// import React from 'react';
// import PlayerFilter from './components/PlayerFilter.jsx';

// const data = {
//   Syrup: {
//     id: 1216463,
//     Tweek: { wins: 0, losses: 1 },
//     Marvale: { wins: 6, losses: 0 }
//   },
//   Tweek: {
//     id: 15768,
//     Marvale: { wins: 0, losses: 0 },
//     Syrup: { wins: 1, losses: 0 }
//   },
//   Marvale: {
//     id: 1189720,
//     Syrup: { wins: 0, losses: 6 },
//     Tweek: { wins: 0, losses: 0 }
//   }
// };
// function App() {
//   return (
//     <div className="App">
//       <PlayerFilter originalObject={data} />
//     </div>
//   );
// }

export default App;

